### ISSUE TITLE
Does this work only on body?       

### ISSUE THREAD

**Issue by ivantacca** [koggdal/scroll-converter#10]
I have a full screen div with a wider div inside and unfortunately it doesn't work:
```html
<body>
	<div class="view" style="background-color: aquamarine;">
		<div class="wider"></div>
	</div>
	<script src="scroll-converter.js"></script>
	<script src="site.js"></script>
</body>
```
```css
body{
	margin:0;
	overflow:hidden;
}
.view{
	height: 100vh;
	width: 100vw;
	overflow-y: hidden;
	overflow-x:scroll;
}
.wider{
        height:50vh;
        width:200vw;
        background-color: blue;
}
```

It only works without specifying the overflow inside each component but the result is not the same
Am I doing something wrong?
